/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/oauth/authorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login with email + password (PKCE step 1) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        email: string;
                        password: string;
                        /** @example dashboard */
                        client_id: string;
                        code_challenge: string;
                        /** @example S256 */
                        code_challenge_method: string;
                        /** @example dashboard:read dashboard:write */
                        scope?: string;
                    };
                };
            };
            responses: {
                /** @description Authorization code */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code?: string;
                        };
                    };
                };
                /** @description Invalid credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange authorization code for access token (PKCE step 2) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        grant_type: "authorization_code" | "refresh_token";
                        /** @example dashboard */
                        client_id: string;
                        /** @description From /oauth/authorize */
                        code: string;
                        code_verifier: string;
                        /** @description For refresh_token grant */
                        refresh_token?: string;
                    };
                };
            };
            responses: {
                /** @description Access token */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user info from token */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            userId?: string;
                            /** Format: uuid */
                            orgId?: string;
                            email?: string;
                            role?: string;
                            name?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dashboard/kpi/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Revenue and order KPIs for a date range */
        get: {
            parameters: {
                query?: {
                    /** @example 2026-01-01 */
                    date_from?: string;
                    /** @example 2026-01-31 */
                    date_to?: string;
                    location_id?: string;
                    terminal_id?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description KPI overview */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["KpiOverview"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dashboard/kpi/by-terminal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** KPIs split per terminal */
        get: {
            parameters: {
                query?: {
                    date_from?: string;
                    date_to?: string;
                    location_id?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Per-terminal KPIs */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            terminals?: {
                                /** Format: uuid */
                                terminalId?: string;
                                terminalCode?: string;
                                terminalName?: string;
                                /** Format: uuid */
                                locationId?: string;
                                locationName?: string;
                                orderCount?: number;
                                revenueGross?: number;
                                revenueNet?: number;
                                avgBasket?: number;
                                indoorCount?: number;
                                takeawayCount?: number;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dashboard/kpi/by-day": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Daily revenue chart data */
        get: {
            parameters: {
                query?: {
                    date_from?: string;
                    date_to?: string;
                    location_id?: string;
                    terminal_id?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Daily breakdown */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            days?: {
                                /** Format: date */
                                day?: string;
                                orderCount?: number;
                                revenueGross?: number;
                                revenueNet?: number;
                                avgBasket?: number;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dashboard/kpi/top-products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Best-selling products */
        get: {
            parameters: {
                query?: {
                    date_from?: string;
                    date_to?: string;
                    location_id?: string;
                    terminal_id?: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Top products */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            products?: {
                                /** Format: uuid */
                                productId?: string;
                                productName?: string;
                                quantitySold?: number;
                                revenueGross?: number;
                                revenueNet?: number;
                                avgPrice?: number;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dashboard/kpi/hourly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Orders per hour heatmap (dow × hour) */
        get: {
            parameters: {
                query?: {
                    date_from?: string;
                    date_to?: string;
                    location_id?: string;
                    terminal_id?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Hourly heatmap data */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            hourly?: {
                                /** @description 0=Sunday … 6=Saturday */
                                dow?: number;
                                /** @description 0–23 */
                                hour?: number;
                                orderCount?: number;
                                revenueGross?: number;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dashboard/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List orders with filters and pagination */
        get: {
            parameters: {
                query?: {
                    location_id?: string;
                    terminal_id?: string;
                    status?: "PENDING" | "CONFIRMED" | "PREPARING" | "READY" | "COMPLETED" | "CANCELLED";
                    mode?: "INDOOR" | "TAKEAWAY";
                    date_from?: string;
                    date_to?: string;
                    page?: number;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated order list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            orders?: components["schemas"]["OrderSummary"][];
                            pagination?: components["schemas"]["Pagination"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dashboard/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Order detail with items, extras, loyalty info */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Order detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrderDetail"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dashboard/orders/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update order status (kitchen workflow) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "PENDING" | "CONFIRMED" | "PREPARING" | "READY" | "COMPLETED" | "CANCELLED";
                    };
                };
            };
            responses: {
                /** @description Updated order */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id?: string;
                            order_number?: string;
                            status?: string;
                            /** Format: date-time */
                            completed_at?: string | null;
                        };
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dashboard/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all categories */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Category list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            categories?: components["schemas"]["Category"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create category */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CategoryInput"];
                };
            };
            responses: {
                /** @description Created category */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Category"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dashboard/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get category by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Category"];
                    };
                };
            };
        };
        /** Update category */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CategoryInput"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Category"];
                    };
                };
            };
        };
        post?: never;
        /** Soft-delete category */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Ok"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dashboard/categories/{id}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload category image */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        image?: string;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id?: string;
                            image_url?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dashboard/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List products */
        get: {
            parameters: {
                query?: {
                    category_id?: string;
                    active_only?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            products?: components["schemas"]["Product"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create product (optionally with initial prices) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProductInput"];
                };
            };
            responses: {
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Product"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dashboard/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get product by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Product"];
                    };
                };
            };
        };
        /** Update product */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ProductInput"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Product"];
                    };
                };
            };
        };
        post?: never;
        /** Soft-delete product */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Ok"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dashboard/products/{id}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload product image */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        image?: string;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id?: string;
                            image_url?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dashboard/products/{id}/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all prices for a product (org-wide, location, terminal) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            prices?: components["schemas"]["Price"][];
                        };
                    };
                };
            };
        };
        /**
         * Upsert prices (bulk)
         * @description Price resolution hierarchy (highest wins):
         *     1. terminal_id + mode
         *     2. location_id + mode
         *     3. org-wide (null + null) + mode
         *     4. BOTH mode as fallback
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        prices: components["schemas"]["PriceInput"][];
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok?: boolean;
                            updated?: number;
                        };
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dashboard/products/{id}/prices/{priceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a specific price entry */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    priceId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Ok"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dashboard/products/{id}/extras": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get extra groups linked to this product */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            extra_groups?: (components["schemas"]["ExtraGroup"] & {
                                options?: components["schemas"]["ExtraOption"][];
                            })[];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Link an extra group to this product */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        extra_group_id: string;
                        /** @default 0 */
                        sort_order?: number;
                    };
                };
            };
            responses: {
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Ok"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dashboard/products/{id}/extras/{groupId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Unlink extra group from product */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    groupId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Ok"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dashboard/extras": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all extra groups */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            extra_groups?: components["schemas"]["ExtraGroup"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create extra group */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ExtraGroupInput"];
                };
            };
            responses: {
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ExtraGroup"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dashboard/extras/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get extra group by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ExtraGroup"];
                    };
                };
            };
        };
        /** Update extra group */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ExtraGroupInput"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ExtraGroup"];
                    };
                };
            };
        };
        post?: never;
        /** Delete extra group (cascades to options) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Ok"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dashboard/extras/{id}/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List options for an extra group */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            options?: components["schemas"]["ExtraOption"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Add option to extra group */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ExtraOptionInput"];
                };
            };
            responses: {
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ExtraOption"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dashboard/extras/{id}/options/{optId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update option */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    optId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ExtraOptionInput"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ExtraOption"];
                    };
                };
            };
        };
        post?: never;
        /** Soft-delete option (preserves order history) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    optId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Ok"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dashboard/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List locations */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            locations?: components["schemas"]["Location"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create location */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LocationInput"];
                };
            };
            responses: {
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Location"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dashboard/locations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Location"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["LocationInput"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Location"];
                    };
                };
            };
        };
        post?: never;
        /** Delete location (requires dashboard:admin) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Ok"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dashboard/terminals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List terminals with live status */
        get: {
            parameters: {
                query?: {
                    location_id?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            terminals?: components["schemas"]["Terminal"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /**
         * Create terminal and generate OAuth credentials
         * @description Returns OAuth `client_id` and `client_secret` **once** in the response.
         *     The secret must be stored immediately in the Android Keystore — it cannot be recovered.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TerminalInput"];
                };
            };
            responses: {
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TerminalCreated"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dashboard/terminals/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Terminal"];
                    };
                };
            };
        };
        /** Update terminal config (triggers RELOAD_MENU if mode changes) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        name?: string;
                        /** @enum {string} */
                        mode?: "INDOOR" | "TAKEAWAY";
                        printer_host?: string;
                        printer_port?: number;
                        printer_width?: number;
                        is_active?: boolean;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Terminal"];
                    };
                };
            };
        };
        post?: never;
        /** Deactivate terminal and revoke OAuth credentials */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Ok"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dashboard/terminals/{id}/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get product visibility overrides for this terminal */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            products?: components["schemas"]["TerminalProductOverride"][];
                        };
                    };
                };
            };
        };
        /** Bulk update product visibility / sold-out (triggers RELOAD_MENU) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        overrides: {
                            /** Format: uuid */
                            product_id: string;
                            /** @default true */
                            is_visible?: boolean;
                            /** @default false */
                            is_sold_out?: boolean;
                            sort_override?: number | null;
                        }[];
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok?: boolean;
                            updated?: number;
                        };
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dashboard/terminals/{id}/commands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Push command to terminal (delivered on next heartbeat) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        command: "RELOAD_MENU" | "SHOW_MESSAGE" | "MAINTENANCE_MODE" | "CLEAR_MAINTENANCE";
                        /**
                         * @example {
                         *       "message": "Wir schliessen in 10 Minuten."
                         *     }
                         */
                        payload?: Record<string, never> | null;
                    };
                };
            };
            responses: {
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id?: string;
                            command?: string;
                            /** Format: date-time */
                            created_at?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dashboard/loyalty/program": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get loyalty program configuration */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoyaltyProgram"];
                    };
                };
                /** @description No program configured yet */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** Create or update loyalty program (upsert) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        name?: string;
                        /** @example 1 */
                        points_per_chf?: number;
                        /** @example 0.01 */
                        chf_per_point?: number;
                        /** @example 100 */
                        min_redeem_points?: number;
                        /** @example 50 */
                        max_redeem_percent?: number;
                        /** @example 365 */
                        expiry_days?: number;
                        is_active?: boolean;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoyaltyProgram"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dashboard/loyalty/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List loyalty customers with search and filter */
        get: {
            parameters: {
                query?: {
                    /** @description Search by name, email, card number, phone */
                    search?: string;
                    tier?: "BRONZE" | "SILVER" | "GOLD" | "PLATINUM";
                    page?: number;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            customers?: components["schemas"]["LoyaltyCustomer"][];
                            pagination?: components["schemas"]["Pagination"];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create loyalty customer */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example DEMO-0001 */
                        card_number: string;
                        first_name?: string;
                        last_name?: string;
                        email?: string;
                        phone?: string;
                        /** Format: date */
                        birth_date?: string;
                    };
                };
            };
            responses: {
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoyaltyCustomer"];
                    };
                };
                /** @description card_number_already_exists */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dashboard/loyalty/customers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoyaltyCustomer"];
                    };
                };
            };
        };
        /** Update customer profile */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        first_name?: string;
                        last_name?: string;
                        email?: string;
                        phone?: string;
                        /** Format: date */
                        birth_date?: string;
                        is_active?: boolean;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoyaltyCustomer"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dashboard/loyalty/customers/{id}/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get transaction history for a customer */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    limit?: number;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            transactions?: components["schemas"]["LoyaltyTransaction"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dashboard/loyalty/customers/{id}/adjust": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Manual point adjustment (bonus, correction, deduction) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description Positive = add, negative = deduct
                         * @example 100
                         */
                        points: number;
                        /** @example Manual bonus – birthday promotion */
                        description?: string;
                    };
                };
            };
            responses: {
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoyaltyTransaction"] & {
                            new_balance?: number;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dashboard/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List dashboard users (requires dashboard:admin) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            users?: components["schemas"]["User"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create dashboard user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                        email: string;
                        password: string;
                        /**
                         * @default MANAGER
                         * @enum {string}
                         */
                        role?: "ADMIN" | "MANAGER" | "VIEWER";
                    };
                };
            };
            responses: {
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                /** @description email_already_exists */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dashboard/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        name?: string;
                        /** @enum {string} */
                        role?: "ADMIN" | "MANAGER" | "VIEWER";
                        is_active?: boolean;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
            };
        };
        post?: never;
        /** Soft-delete user (OWNER cannot be deleted) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Ok"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dashboard/users/{id}/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset user password */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        new_password: string;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Ok"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @example invalid_request */
            error?: string;
            /** @example Field is required */
            message?: string;
        };
        Ok: {
            /** @example true */
            ok?: boolean;
        };
        Pagination: {
            /** @example 1 */
            current_page?: number;
            /** @example 5 */
            total_pages?: number;
            /** @example 243 */
            total_items?: number;
            /** @example 50 */
            items_per_page?: number;
        };
        /** @description Translations for display name in supported languages */
        Translations: {
            /** @example Klassischer Käseburger */
            de?: string;
            /** @example Cheeseburger classique */
            fr?: string;
            /** @example Cheeseburger classico */
            it?: string;
            /** @example Classic Cheeseburger */
            en?: string;
        };
        TaxBreakdownItem: {
            /** @example 8.1 */
            rate?: number;
            /** @example 9.25 */
            net?: number;
            /** @example 0.75 */
            tax?: number;
            /** @example 10 */
            gross?: number;
        };
        TokenResponse: {
            access_token?: string;
            /** @example Bearer */
            token_type?: string;
            /** @example 3600 */
            expires_in?: number;
            refresh_token?: string;
            scope?: string;
        };
        Category: {
            /** Format: uuid */
            id?: string;
            /** @example Burger */
            name?: string;
            translations?: components["schemas"]["Translations"];
            /** @example /uploads/cat_burger.jpg */
            image_url?: string | null;
            /** @example 1 */
            sort_order?: number;
            is_active?: boolean;
            /** @example 5 */
            product_count?: number;
        };
        CategoryInput: {
            /** @example Burger */
            name: string;
            translations?: components["schemas"]["Translations"];
            /** @example 1 */
            sort_order?: number;
        };
        Product: {
            /** Format: uuid */
            id?: string;
            /** @example Classic Cheeseburger */
            name?: string;
            translations?: components["schemas"]["Translations"];
            description?: string | null;
            image_url?: string | null;
            /** @example BURG-001 */
            sku?: string | null;
            /** @example 8.1 */
            tax_rate?: number;
            /** @example 0 */
            sort_order?: number;
            is_active?: boolean;
            /** Format: uuid */
            category_id?: string;
            /** @example Burger */
            category_name?: string;
            /** @example 9.90 */
            base_price?: string | null;
            /** Format: date-time */
            created_at?: string;
        };
        ProductInput: {
            name: string;
            translations?: components["schemas"]["Translations"];
            description?: string;
            /** Format: uuid */
            category_id?: string;
            sku?: string;
            /**
             * @description VAT rate in %. Swiss rates: 8.1 (standard), 2.6 (food takeaway)
             * @example 8.1
             */
            tax_rate?: number;
            sort_order?: number;
            prices?: components["schemas"]["PriceInput"][];
        };
        Price: {
            /** Format: uuid */
            id?: string;
            /** @enum {string} */
            mode?: "INDOOR" | "TAKEAWAY" | "BOTH";
            /** @example 9.90 */
            price?: string;
            /** @example CHF */
            currency?: string;
            /** Format: uuid */
            location_id?: string | null;
            location_name?: string | null;
            /** Format: uuid */
            terminal_id?: string | null;
            terminal_name?: string | null;
            /** Format: date */
            valid_from?: string | null;
            /** Format: date */
            valid_until?: string | null;
        };
        PriceInput: {
            /**
             * Format: uuid
             * @description null = org-wide
             */
            location_id?: string | null;
            /**
             * Format: uuid
             * @description null = all terminals
             */
            terminal_id?: string | null;
            /** @enum {string} */
            mode: "INDOOR" | "TAKEAWAY" | "BOTH";
            /** @example 9.90 */
            price: string;
            /** @example CHF */
            currency?: string;
            /** Format: date */
            valid_from?: string | null;
            /** Format: date */
            valid_until?: string | null;
        };
        ExtraGroup: {
            /** Format: uuid */
            id?: string;
            /** @example Choose your size */
            name?: string;
            translations?: components["schemas"]["Translations"];
            /** @enum {string} */
            selection_type?: "SINGLE" | "MULTIPLE";
            /** @example 0 */
            min_selections?: number;
            /** @example 3 */
            max_selections?: number | null;
            is_required?: boolean;
            sort_order?: number;
            /** @example 3 */
            option_count?: number;
        };
        ExtraGroupInput: {
            name: string;
            translations?: components["schemas"]["Translations"];
            /**
             * @default MULTIPLE
             * @enum {string}
             */
            selection_type: "SINGLE" | "MULTIPLE";
            /** @default 0 */
            min_selections: number;
            max_selections?: number | null;
            /** @default false */
            is_required: boolean;
            /** @default 0 */
            sort_order: number;
        };
        ExtraOption: {
            /** Format: uuid */
            id?: string;
            /** @example Extra Cheese */
            name?: string;
            translations?: components["schemas"]["Translations"];
            /** @example 1.50 */
            price_add?: string;
            is_active?: boolean;
            sort_order?: number;
        };
        ExtraOptionInput: {
            name: string;
            translations?: components["schemas"]["Translations"];
            /**
             * @default 0.00
             * @example 1.50
             */
            price_add: string;
            /** @default 0 */
            sort_order: number;
        };
        Location: {
            /** Format: uuid */
            id?: string;
            /** @example Filiale Zürich HB */
            name?: string;
            address?: string | null;
            city?: string | null;
            /** @example CH */
            country?: string;
            /** @example Europe/Zurich */
            timezone?: string;
            is_active?: boolean;
            /** @example 3 */
            terminal_count?: number;
            /** Format: date-time */
            created_at?: string;
        };
        LocationInput: {
            name: string;
            address?: string;
            city?: string;
            /** @default CH */
            country: string;
            /** @default Europe/Zurich */
            timezone: string;
        };
        Terminal: {
            /** Format: uuid */
            id?: string;
            /** @example ZH01-T1 */
            terminal_code?: string;
            /** @example Kasse 1 Eingang */
            name?: string;
            /** @enum {string} */
            mode?: "INDOOR" | "TAKEAWAY";
            /** @enum {string} */
            status?: "ONLINE" | "OFFLINE" | "MAINTENANCE" | "ERROR";
            /** Format: date-time */
            last_heartbeat_at?: string | null;
            /** @example 1.0.2 */
            app_version?: string | null;
            vitals?: {
                /** @example 85 */
                battery_level?: number;
                /** @example 4096 */
                storage_free_mb?: number;
                /** @example wifi */
                network_type?: string;
            } | null;
            printer_host?: string | null;
            /** @example 9100 */
            printer_port?: number;
            /** @example 80 */
            printer_width?: number;
            is_active?: boolean;
            /** Format: uuid */
            location_id?: string;
            location_name?: string;
            /** Format: date-time */
            created_at?: string;
        };
        TerminalInput: {
            /** Format: uuid */
            location_id: string;
            /** @example ZH01-T1 */
            terminal_code: string;
            /** @example Kasse 1 Eingang */
            name: string;
            /**
             * @default INDOOR
             * @enum {string}
             */
            mode: "INDOOR" | "TAKEAWAY";
            printer_host?: string | null;
            /** @default 9100 */
            printer_port: number;
            /** @default 80 */
            printer_width: number;
        };
        TerminalCreated: {
            terminal?: components["schemas"]["Terminal"];
            /** @description OAuth credentials shown ONCE. Store client_secret in Android Keystore. */
            oauth?: {
                /** @example terminal_zh01_t1_a1b2c3d4 */
                client_id?: string;
                /** @example abc123... */
                client_secret?: string;
                note?: string;
            };
        };
        TerminalProductOverride: {
            /** Format: uuid */
            id?: string;
            name?: string;
            /** Format: uuid */
            category_id?: string;
            category_name?: string;
            is_visible?: boolean;
            is_sold_out?: boolean;
            sort_override?: number | null;
        };
        OrderSummary: {
            /** Format: uuid */
            id?: string;
            /** @example T1-0042 */
            order_number?: string;
            /** @enum {string} */
            status?: "PENDING" | "CONFIRMED" | "PREPARING" | "READY" | "COMPLETED" | "CANCELLED";
            /** @enum {string} */
            mode?: "INDOOR" | "TAKEAWAY";
            /** @example 9.25 */
            subtotal_net?: string;
            /** @example 10.00 */
            subtotal_gross?: string;
            /** @example 0.00 */
            discount_amount?: string;
            /** @example 1.00 */
            loyalty_discount?: string;
            /** @example 9.00 */
            total_gross?: string;
            /** @enum {string|null} */
            payment_method?: "CARD" | "TWINT" | "BONCARD" | "CASH" | null;
            payment_status?: string | null;
            tax_breakdown?: components["schemas"]["TaxBreakdownItem"][];
            location_name?: string;
            terminal_name?: string;
            terminal_code?: string;
            customer_first_name?: string | null;
            customer_last_name?: string | null;
            customer_card?: string | null;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            completed_at?: string | null;
        };
        OrderDetail: components["schemas"]["OrderSummary"] & {
            /** @enum {string|null} */
            customer_tier?: "BRONZE" | "SILVER" | "GOLD" | "PLATINUM" | null;
            notes?: string | null;
            items?: {
                /** Format: uuid */
                id?: string;
                product_name?: string;
                quantity?: number;
                unit_price?: string;
                extras_price?: string;
                tax_rate?: number;
                tax_amount?: string;
                total_net_price?: string;
                total_gross_price?: string;
                notes?: string | null;
                extras?: {
                    extra_name?: string;
                    price_add?: string;
                }[];
            }[];
        };
        KpiOverview: {
            orderCount?: number;
            revenueGross?: number;
            revenueNet?: number;
            taxTotal?: number;
            avgBasket?: number;
            maxBasket?: number;
            discountTotal?: number;
            loyaltyDiscountTotal?: number;
            indoorCount?: number;
            takeawayCount?: number;
            indoorRevenue?: number;
            takeawayRevenue?: number;
            loyaltyCustomerCount?: number;
            taxBreakdown?: components["schemas"]["TaxBreakdownItem"][];
        };
        LoyaltyProgram: {
            /** Format: uuid */
            id?: string;
            /** @example Orderzilla Punkte */
            name?: string;
            /**
             * @description Points earned per CHF spent
             * @example 1
             */
            points_per_chf?: number;
            /**
             * @description CHF value per point
             * @example 0.01
             */
            chf_per_point?: number;
            /** @example 100 */
            min_redeem_points?: number;
            /**
             * @description Max % of order total that can be paid with points
             * @example 50
             */
            max_redeem_percent?: number;
            /** @example 365 */
            expiry_days?: number;
            is_active?: boolean;
        };
        LoyaltyCustomer: {
            /** Format: uuid */
            id?: string;
            /** @example DEMO-0001 */
            card_number?: string;
            first_name?: string | null;
            last_name?: string | null;
            email?: string | null;
            phone?: string | null;
            /** Format: date */
            birth_date?: string | null;
            /** @example 250 */
            points_balance?: number;
            total_points_earned?: number;
            total_points_redeemed?: number;
            /** @example 124.50 */
            total_spent?: string;
            /** @enum {string} */
            tier?: "BRONZE" | "SILVER" | "GOLD" | "PLATINUM";
            is_active?: boolean;
            /** Format: date-time */
            created_at?: string;
        };
        LoyaltyTransaction: {
            /** Format: uuid */
            id?: string;
            /** @enum {string} */
            type?: "EARN" | "REDEEM" | "ADJUSTMENT" | "EXPIRY";
            /** @example 10 */
            points?: number;
            /** @example 260 */
            balance_after?: number;
            /** @example Order T1-0042 */
            description?: string;
            order_number?: string | null;
            order_total?: string | null;
            /** Format: date-time */
            created_at?: string;
        };
        User: {
            /** Format: uuid */
            id?: string;
            /** @example Max Muster */
            name?: string;
            /** @example max@restaurant.ch */
            email?: string;
            /** @enum {string} */
            role?: "OWNER" | "ADMIN" | "MANAGER" | "VIEWER";
            is_active?: boolean;
            /** Format: date-time */
            created_at?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
